version: '3.8'

services:
  lantern:
    build: .
    container_name: lantern-hedge-bot
    restart: unless-stopped

    # Environment variables - REPLACE WITH YOUR VALUES
    environment:
      # GRVT Configuration
      - GRVT_API_KEY=${GRVT_API_KEY}
      - GRVT_PRIVATE_KEY=${GRVT_PRIVATE_KEY}

      # Lighter Configuration
      - LIGHTER_API_KEY=${LIGHTER_API_KEY}
      - LIGHTER_PRIVATE_KEY=${LIGHTER_PRIVATE_KEY}
      - LIGHTER_API_HOST=${LIGHTER_API_HOST:-https://chain.lighter.xyz/api}

      # Trading Parameters
      - SYMBOL=${SYMBOL:-BTC}
      - SIZE=${SIZE:-0.3}
      - TARGET_CYCLES=${TARGET_CYCLES:-5}
      - SPREAD_BPS=${SPREAD_BPS:-10}
      - CYCLE_INTERVAL=${CYCLE_INTERVAL:-60}
      - ORDER_TIMEOUT=${ORDER_TIMEOUT:-30}

      # Safety Parameters
      - MAX_POSITION=${MAX_POSITION:-10.0}
      - REBALANCE_TOLERANCE=${REBALANCE_TOLERANCE:-0.5}
      - EMERGENCY_STOP_LOSS=${EMERGENCY_STOP_LOSS:-5.0}

      # Control Parameters
      - BLOCK_ORDERS=${BLOCK_ORDERS:-false}
      - BLOCK_ORDER_RECREATION=${BLOCK_ORDER_RECREATION:-false}

    # Mount logs directory to persist logs
    volumes:
      - ./logs:/app/logs
