version: '3.8'

services:
  lantern:
    build: .
    container_name: lantern-hedge-bot
    restart: unless-stopped

    # Environment variables - REPLACE WITH YOUR VALUES
    environment:
      # GRVT Configuration
      - GRVT_TRADING_ACCOUNT_ID=${GRVT_TRADING_ACCOUNT_ID}
      - GRVT_PRIVATE_KEY=${GRVT_PRIVATE_KEY}
      - GRVT_API_KEY=${GRVT_API_KEY}
      - GRVT_ENVIRONMENT=prod

      # Lighter Configuration
      - LIGHTER_ACCOUNT_INDEX=${LIGHTER_ACCOUNT_INDEX}
      - LIGHTER_API_KEY_INDEX=${LIGHTER_API_KEY_INDEX}
      - LIGHTER_PRIVATE_KEY=${LIGHTER_PRIVATE_KEY}

      # Trading Parameters
      - EXCHANGE=${EXCHANGE:-grvt}
      - TICKER=${TICKER:-HYPE}
      - SIZE=${SIZE:-10}
      - ITERATIONS=${ITERATIONS:-20}

      # Cycle Mode Parameters
      - BUILD_UP_ITERATIONS=${BUILD_UP_ITERATIONS:-30}
      - HOLD_TIME=${HOLD_TIME:-1800}
      - CYCLES=${CYCLES:-999999}
      - DIRECTION=${DIRECTION:-long}

      # Advanced Parameters
      - PRICE_TOLERANCE=${PRICE_TOLERANCE:-3}
      - MIN_ORDER_LIFETIME=${MIN_ORDER_LIFETIME:-30}
      - REBALANCE_THRESHOLD=${REBALANCE_THRESHOLD:-0.15}
      - AUTO_REBALANCE=${AUTO_REBALANCE:-true}
      - FILL_TIMEOUT=${FILL_TIMEOUT:-5}

    # Mount logs directory to persist logs
    volumes:
      - ./logs:/app/logs
