version: '3.8'

services:
  lantern:
    build:
      context: .
      dockerfile: config/Dockerfile
    container_name: lantern-hedge-bot-v3
    restart: unless-stopped

    # Environment variables - can be set in .env file or here
    environment:
      # GRVT Configuration (Required)
      - GRVT_API_KEY=${GRVT_API_KEY}
      - GRVT_PRIVATE_KEY=${GRVT_PRIVATE_KEY}
      - GRVT_TRADING_ACCOUNT_ID=${GRVT_TRADING_ACCOUNT_ID}
      - GRVT_ENVIRONMENT=${GRVT_ENVIRONMENT:-prod}

      # Lighter Configuration (Required)
      - LIGHTER_PRIVATE_KEY=${LIGHTER_PRIVATE_KEY}
      - LIGHTER_ACCOUNT_INDEX=${LIGHTER_ACCOUNT_INDEX:-0}
      - LIGHTER_API_KEY_INDEX=${LIGHTER_API_KEY_INDEX:-0}

      # Trading Parameters (Optional - have defaults)
      - TRADING_SYMBOL=${TRADING_SYMBOL:-BNB}
      - TRADING_SIZE=${TRADING_SIZE:-0.1}
      - CYCLE_TARGET=${CYCLE_TARGET:-5}
      - CYCLE_HOLD_TIME=${CYCLE_HOLD_TIME:-180}

    # Mount logs directory and .env file
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro

    # Health check - verify the bot process is running
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'python.*hedge_bot_v3' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Optional: Set logging driver
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
