version: '3.8'

services:
  lantern:
    build:
      context: .
      dockerfile: config/Dockerfile
    container_name: lantern-funding-bot
    restart: unless-stopped

    # Environment variables - can be set in .env file or here
    environment:
      # Exchange Selection (Optional - defaults to GRVT vs Lighter)
      - EXCHANGE_A=${EXCHANGE_A:-GRVT}
      - EXCHANGE_B=${EXCHANGE_B:-Lighter}

      # GRVT Configuration (Required if using GRVT)
      - GRVT_API_KEY=${GRVT_API_KEY}
      - GRVT_PRIVATE_KEY=${GRVT_PRIVATE_KEY}
      - GRVT_TRADING_ACCOUNT_ID=${GRVT_TRADING_ACCOUNT_ID}
      - GRVT_ENVIRONMENT=${GRVT_ENVIRONMENT:-prod}

      # Lighter Configuration (Required if using Lighter)
      - LIGHTER_PRIVATE_KEY=${LIGHTER_PRIVATE_KEY}
      - LIGHTER_ACCOUNT_INDEX=${LIGHTER_ACCOUNT_INDEX:-0}
      - LIGHTER_API_KEY_INDEX=${LIGHTER_API_KEY_INDEX:-0}

      # Binance Configuration (Required if using Binance)
      - BINANCE_API_KEY=${BINANCE_API_KEY:-}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY:-}

      # Backpack Configuration (Required if using Backpack)
      - BACKPACK_PUBLIC_KEY=${BACKPACK_PUBLIC_KEY:-}
      - BACKPACK_SECRET_KEY=${BACKPACK_SECRET_KEY:-}

      # Trading Parameters (Required)
      - TRADING_SYMBOL=${TRADING_SYMBOL:-BTC}
      - TRADING_SIZE=${TRADING_SIZE:-0.1}
      - MAX_POSITION=${MAX_POSITION:-10}

      # Funding Rate Strategy Parameters (Required)
      - FUNDING_BUILD_THRESHOLD_APR=${FUNDING_BUILD_THRESHOLD_APR:-0.05}
      - FUNDING_CLOSE_THRESHOLD_APR=${FUNDING_CLOSE_THRESHOLD_APR:-0.02}
      - FUNDING_CHECK_INTERVAL=${FUNDING_CHECK_INTERVAL:-300}

      # Pushover Notifications (Optional)
      - PUSHOVER_USER_KEY=${PUSHOVER_USER_KEY:-}
      - PUSHOVER_API_TOKEN=${PUSHOVER_API_TOKEN:-}

      # Telegram Bot (Optional)
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}

    # Health check - verify the bot process is running
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'python.*hedge_bot_funding' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Optional: Set logging driver
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
