[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "pip install grvt-pysdk"
]

[start]
cmd = "python3 hedge_mode.py --exchange grvt --ticker HYPE --size 1 --build-up-iterations 20 --hold-time 1800 --cycles 999999"
