version: '3.8'

services:
  lantern:
    build:
      context: ..
      dockerfile: config/Dockerfile
    container_name: lantern-hedge-bot
    restart: unless-stopped

    # Environment variables - REPLACE WITH YOUR VALUES
    environment:
      # GRVT Configuration
      - GRVT_TRADING_ACCOUNT_ID=${GRVT_TRADING_ACCOUNT_ID}
      - GRVT_API_KEY=${GRVT_API_KEY}
      - GRVT_PRIVATE_KEY=${GRVT_PRIVATE_KEY}
      - GRVT_ENVIRONMENT=${GRVT_ENVIRONMENT:-prod}

      # Lighter Configuration
      - LIGHTER_API_PRIVATE_KEY=${LIGHTER_API_PRIVATE_KEY}
      - LIGHTER_ACCOUNT_INDEX=${LIGHTER_ACCOUNT_INDEX}
      - LIGHTER_API_KEY_INDEX=${LIGHTER_API_KEY_INDEX}
      - LIGHTER_API_HOST=${LIGHTER_API_HOST:-https://mainnet.zklighter.elliot.ai}

      # Basic Trading Parameters
      - TRADING_SYMBOL=${TRADING_SYMBOL:-BTC}
      - TRADING_SIZE=${TRADING_SIZE:-0.3}
      - TRADING_DIRECTION=${TRADING_DIRECTION:-long}

      # Cycle Parameters
      - CYCLE_TARGET=${CYCLE_TARGET:-5}
      - CYCLE_INTERVAL=${CYCLE_INTERVAL:-60}
      - CYCLE_HOLD_TIME=${CYCLE_HOLD_TIME:-180}

      # Order Parameters
      - ORDER_TIMEOUT=${ORDER_TIMEOUT:-30}
      - ORDER_SPREAD_BPS=${ORDER_SPREAD_BPS:-10}
      - ORDER_MAX_RETRIES=${ORDER_MAX_RETRIES:-3}

      # Safety Parameters
      - SAFETY_MAX_POSITION=${SAFETY_MAX_POSITION:-10.0}
      - SAFETY_REBALANCE_TOLERANCE=${SAFETY_REBALANCE_TOLERANCE:-0.5}
      - SAFETY_EMERGENCY_STOP_LOSS=${SAFETY_EMERGENCY_STOP_LOSS:-5.0}

      # Control Parameters
      - CONTROL_BLOCK_ORDERS=${CONTROL_BLOCK_ORDERS:-false}
      - CONTROL_BLOCK_ORDER_RECREATION=${CONTROL_BLOCK_ORDER_RECREATION:-false}

    # Mount logs directory to persist logs
    volumes:
      - ../logs:/app/logs
      - ../.env:/app/.env:ro
